### ISSUE TITLE
problem with infering the main_var from res

### ISSUE THREAD

**Issue by MrX-NGS** [FrederickHuangLin/ANCOM#11]
Hi,

How to infer the main_var value from final results output?

  res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
                                              alpha, adj_formula, rand_formula)

I can only able to see the value is passing the cutoff 0.6,0.7,0.8 and 0.9 as TRUE or FALSE. if it is TRUE then how i will know the value of main_var contributing to that value? If my main_var is disease stage 1 vs disease stage 2 then i like to see the value passing the cutoff 0.7 say 0.74 representing which variable side stage1 or stage2?

Any suggestions would be helpful to understand whether the main_var is under or over represented!! 

Thanks in advance!
Bala

**Comment by samd1993** [comment]
I would also be curious if there is an answer for this. Having a similar issue interpreting the results.

**Comment by samd1993** [comment]
My 2 cents woul be to plot the relative abundance of each taxa of interest against the variable of interest and that will tell you the “meaning” of the ANCOM result. 

Currently trying to figure out how to modify the script to add an upregulated and downregulated column to the main results.

**Comment by FrederickHuangLin** [comment]
Dear All,

Thank you for your interest in using ANCOM!

Hi Bala, if I understand your question correctly, you basically are looking for effect size (e.g. the coefficient of "disease stage 2 - disease stage 1" on microbial absolute abundances), is that right?

To make the long story short, unfortunately, ANCOM is not able to provide you with such information. As you can see from the ANCOM outputs, there are some cutoff values ranging from 0.6 to 0.9 labeled as TRUE or FALSE. You can choose different cutoff values based on whether you want a more conservative or more relaxed FDR control, but essentially, TRUE tells you the variable of interest (e.g. "disease stage 2 - disease stage 1" since "disease stage 1" will be chosen as the reference by default in R) has a statistically significant impact on the microbial absolute abundances; otherwise, it will be labeled as FALSE. Thus, you cannot really tell "how much" the impact is, and "which direction" the impact is.

I agree with samd1993, you can visualize the ANCOM results by the relative abundance plot (actually this is what we have been doing in our group when using ANCOM), but keep in mind that ANCOM is designed for testing absolute abundances, not relative abundances (values between 0 and 1), you need to be cautious in interpreting results using relative abundances.

The good news is that we realize the limitation of ANCOM and we proposed a brand-new method that provides effect sizes, p-values, and so on. The paper has been accepted in Nature Communications recently and as soon as it gets published, we will release the corresponding R package as well.

Hope it helps,

Huang

**Comment by MrX-NGS** [comment]
Thanks for your clear answer! I wonder how one of the main_var values chosen as reference by default? Is it depend on the naming of the variables based on alphabetical order? How to tweak the code if i want disease stage 2 as reference instead of disease stage 1?

Bala

**Comment by FrederickHuangLin** [comment]
Hi Bala,

Yes, the factor variable is ordered alphabetically by default. You can change it by manually specifying the order, see this [post](https://stackoverflow.com/questions/2375587/reorder-levels-of-a-factor-without-changing-order-of-values) for details.

Best,

Huang

**Comment by KMKemp** [comment]
Great resource, Huang! Im looking forward to also using your latest ANCOM-BC. How do you recommend plotting the abundance data? This question is a follow-up to your suggestion above from May 29th... 

"I agree with samd1993, you can visualize the ANCOM results by the relative abundance plot (actually this is what we have been doing in our group when using ANCOM), but keep in mind that ANCOM is designed for testing absolute abundances, not relative abundances (values between 0 and 1), you need to be cautious in interpreting results using relative abundances."

Do you recommend **plotting transformed absolute count data** to take into account library sizes? So, like EdgeR TMM transformation or using the processed feature table form ANCOM-II. Or do you just take the raw data and transform it for **plotting relative abundance**?
