### ISSUE TITLE
Inf and zero W values  

### ISSUE THREAD

**Issue by ajcardenasb** [FrederickHuangLin/ANCOM#16]
Hello,

I'm getting only "inf" and zeros from ANCOM output. I used different datasets and always get the same, but I can reproduce your example data successfully. I'm wondering If I am not pre-treating my data in a certain way needed but I also noticed your examples use different types of data, e.g. ecam-table-taxa.tsv has relative abundances and moving-pics-table.tsv has counts. 

Any ideas why I get this output? See below the code I used
Thanks,
Anny

#Data in
map=read.table("./Input_files/skeleton16S-metadata.txt", header = TRUE, row.names = 1, sep ='\t')
map$ID=rownames(map)
otu.p=read.table("./outputs/OTU_table_noConta.txt", header = TRUE)

### Filtering
#Filter out OTUs with less than 10 counts across all samples
otu.f1=subset(otu.p, rowSums(otu.p) > 10)
#filter out all of the OTUs that only appear in one sample
otu.f2=otu.f1[rowSums(otu.f1 > 0) > 3, ]
otu=otu.f2

#ANCOM
otu.gon.t=otu.f2[grepl("G[CH][1-6]B", names(otu.f2))]
met.gon.t=subset(map, rownames(map) %in%  names(otu.gon.t))
otu.gon_t_prepro=feature_table_pre_process(otu.gon.t, met.gon.t, "ID", group_var = "Treatment", out_cut = 0.05, zero_cut = 0.90, lib_cut = 1000, neg_lb =FALSE)
otu.gon_t_feature_table = otu.gon_t_prepro$feature_table 
otu.gon_t_meta_data = otu.gon_t_prepro$meta_data 
otu.gon_t_struc_zero = otu.gon_t_prepro$structure_zeros
otu.gon_t_res = ANCOM(otu.gon_t_feature_table , otu.gon_t_meta_data, otu.gon_t_struc_zero, main_var= "Treatment", p_adj_method= "fdr",  alpha = 0,05, adj_formula=  NULL, rand_formula= NULL)
otu.gon_t_df=as.data.frame(otu.gon_t_res$out)

**Comment by FrederickHuangLin** [comment]
Hi,

My sincere apology for responding late! 

`W = Inf` indicates the corresponding taxon is considered as structural zero (completely absent in some groups). It is commonly seen when your dataset is extremely sparse.

Could you try to release all filtering criteria and see if the result will change? For example, try to use `otu.p` instead of `otu.f2` and set `lib_cut = 0` (this will keep all samples).

I notice that you have this line of code:

`otu.gon.t=otu.f2[grepl("G[CH][1-6]B", names(otu.f2))]`

Could you also check the sample size as well as the sparsity of the resulting feature table?

Best,

Huang
