### ISSUE TITLE
Absolute or relative abundance?

### ISSUE THREAD

**Issue by opalmeira** [FrederickHuangLin/ANCOM#20]
Hello FrederickHuangLin!
Thank you very much for your scripts (ancom_v2.1.R and ecam.R).
I´m going to run them on my data sets, but I would like to understand your scripts first by running it on your data set (ecam-table-taxa.tsv) which I downloaded and noticed that the values are in relative abundance. However in "ReadMe" says "Note that this is the absolute abundance table, do not transform it to relative abundance table (where the column totals are equal to 1)." 
Should I run with this file or can you provide the file with absolute abundance?

Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @opalmeira 

Thank you for using ANCOM!

You are right, the ecam dataset (`ecam-table-taxa.tsv)`) is not a good example. This dataset contains relative abundance data rather than absolute abundance data. We use this dataset anyway just for a demonstration purpose, however, we will use a better example dataset once ANCOM is submitted to Bioconductor.

Meanwhile, we still recommend you use "absolute abundance table, and do not transform it to relative abundance table (where the column totals are equal to 1)" while analyzing your own data. 

Best,

Huang

**Comment by mnhuda** [comment]
@FrederickHuangLin , Would you please comment on the library size normalization? Do we need to use single rarefied data or ANCOM’s internal transformation addresses the library size variation across samples?

**Comment by FrederickHuangLin** [comment]
Hi @mnhuda, the rarefication or any other library size normalization is not necessary (also not recommended) for ANCOM as its internal transformation has addressed this problem as you mentioned!

Best,

Huang
