### ISSUE TITLE
data/ecam-table-taxa.tsv is relativae abundance?

### ISSUE THREAD

**Issue by BinhongLiu** [FrederickHuangLin/ANCOM#22]
Hi,
    Thanks for the development of this grateful DA analysis tool!
    I just found that the demo data (data/ecam-table-taxa.tsv) that been passed to the _feature_table_pre_process_ script was a relative abundance table. Should not it be an absolute abundance table? Thanks!
Best wishes!

**Comment by FrederickHuangLin** [comment]
Hi @BinhongLiu,

Thank you for using ANCOM!

You are right, the ecam dataset (ecam-table-taxa.tsv)) is not a good example. This dataset contains relative abundance data rather than absolute abundance data. We use this dataset anyway just for a demonstration purpose, however, we switch to a better example dataset once ANCOM is submitted to Bioconductor.

Meanwhile, we still recommend you use "absolute abundance table, and do not transform it to relative abundance table (where the column totals are equal to 1)" while analyzing your own data.

Best,

Huang
