### ISSUE TITLE
recommend plotting of data? 

### ISSUE THREAD

**Issue by KMKemp** [FrederickHuangLin/ANCOM#24]
Great resource, Huang! Im looking forward to also using your latest ANCOM-BC. How do you recommend plotting the abundance data? This question is a follow-up to your suggestion above from May 29th... 

"I agree with samd1993, you can visualize the ANCOM results by the relative abundance plot (actually this is what we have been doing in our group when using ANCOM), but keep in mind that ANCOM is designed for testing absolute abundances, not relative abundances (values between 0 and 1), you need to be cautious in interpreting results using relative abundances."

Do you recommend **plotting transformed absolute count data** to take into account library sizes? So, like EdgeR TMM transformation or using the processed feature table form ANCOM-II. Or do you just take the raw data and transform it for **plotting relative abundance**?

_Originally posted by @KMKemp in https://github.com/FrederickHuangLin/ANCOM/issues/11#issuecomment-740679276_

**Comment by FrederickHuangLin** [comment]
Hi @KMKemp,

Thanks for your interest in ANCOM and ANCOMBC! Per your question, here are my suggestions:

1. Visualize the normalized abundance data. As you mentioned, you can first normalize the observed abundance data by some normalization factors (e.g. TMM), and then plot the normalized abundance data. However, ANCOM does not have the normalization step, so there are no normalization factors generated by ANCOM. If you are using ANCOM-BC, you can follow section 3.47 of the [vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html) here to obtain normalization factors (sampling fractions) and normalized abundance data.

2. Visualize the relative abundance data, which is also commonly done in microbiome research. For example, the "microbiome" R package has a few [functions](https://microbiome.github.io/tutorials/Composition.html) for visualizing relative abundances. 

3. Visualize the centered log-ratio (CLR) instead of relative abundances using volcano plots as shown in the tutorial, you can also find an [eaxmple](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2020.11%2Fdata%2Ftutorials%2Fmoving-pictures%2Fancom-subject.qzv) here in QIIME2.

Best,
Huang

**Comment by KMKemp** [comment]
Thank you for the clarity and helpful suggestions! I'm closing this out!
