### ISSUE TITLE
Issues with multiple group comparasion 

### ISSUE THREAD

**Issue by SantanuMBLab** [FrederickHuangLin/ANCOM#28]
Hi,
I was trying to perform ANCOM-BC for multiple-group comparisons  however in the preprocessing step got an error the error 

"Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels"
The "group.var" in this case consist of three levels. 

The scripts used is:
# ANCOM-BC for multiple groups 
meta_data <- sample_data(ps_ra)
feature.table = otu_table(ps_ra); sample.var = "UID"; group.var = "DrinkVolume" ; 
zero.cut = 0.90; lib.cut = 1000; neg.lb = TRUE
pre.process = feature_table_pre_process(feature.table, meta_data, sample.var, 
                                        group.var, zero.cut, lib.cut, neg.lb)

Kindly let me know, how to solve this issue.
Thanks in advance!

**Comment by FrederickHuangLin** [comment]
Hi @SantanuMBLab,

It seems you are using ANCOM-BC not ANCOM. Kindly note that ANCOM-BC has been published as an [R package](https://bioconductor.org/packages/release/bioc/html/ANCOMBC.html) on Bioconductor.

It is highly recommended using the R package instead of the standalone code since the code is no longer actively maintained. 

If you encounter any issues when using the ANCOMBC R package, please post your question [here](https://github.com/FrederickHuangLin/ANCOMBC/issues).

Best,
Huang
