### ISSUE TITLE
ANCOM returning 0 differentially abundant taxa. When its clear there are differentially abundant taxa. 

### ISSUE THREAD

**Issue by DJFast** [FrederickHuangLin/ANCOM#29]
Hey everyone, apologies for posting again this week, but I am hoping to get some insights on whats happening with ANCOM runs. Thanks again for this valuable open source resource. 

So basically, ANCOM seems to be running perfectly fine. OTU IDs are assigned properly, the metadata is loaded, and the feature table seems to be created fine. However, when I run ANCOM by subject-ID, I return 0 deferentially abundant taxa. This happens if I run it with 2 subjects of with 7. I know this can't be accurate, because if I look at the raw data, I can see many many taxa with drastically different read numbers between subjects. 

Incidentally, I am wondering why if I have 7 subjects why does ANCOM return a graph with only 6 facets. This makes it seem as though ANCOM is comparing all subjects to subject 1? Perhaps this is the issue. Any help here would be greatly appreciated. I really don't understand why its returning no differentially abundant taxa.

**Comment by FrederickHuangLin** [comment]
Hi @DJFast,

My apologies for responding late. 

I see your attached example data set has two subjects, and your covariate of interest is "Subject" itself. In this case, the test statistic is not valid, for example, think about the simple t-test, since you each group (Subject in your case) contains only one observation, the standard error is not able to be calculated.

As for the case of 7 subjects, again, you should define the "group" variable such that each group has more than 2 observations. Therefore, if the "group" variable is still "Subject", even though you have more subjects, since within each subject, the number of observation is still one (the subject him/herself), the algorithm is not able to compute the standard error.

Best,
Huang
