### ISSUE TITLE
R script in zip folder for download is incomplete

### ISSUE THREAD

**Issue by pricesdr** [FrederickHuangLin/ANCOM#33]
The ancom_v2.1.R script contained in the scripts file in the zipped folder for download does not match the same script listed here in the github. It's missing key components to properly include out and is completely missing the commands to create and include fig in the res output when running ANCOM.

**Comment by FrederickHuangLin** [comment]
Hi @pricesdr,

Did you mean the zip folder of "Third release of ANCOM"? You are right, that zip folder is not up-to-date. I would recommend downloading the whole repository directly. 

The ANCOM function in this repository is not actively maintained due to the limited resources I currently have. It is planned to be incorporated into the `ANCOMBC` R package later.

Best,
Huang
