### ISSUE TITLE
Alternative use of ANCOM

### ISSUE THREAD

**Issue by Somebodyatthdoor** [FrederickHuangLin/ANCOM#36]
I've been thinking about alternative scenarios where ANCOM might be useful for analyses. I am currently trying to compare the presence and absence of a group of metabolic genes across two groups of microbial genomes. In many ways the data is very similar to a 16S OTU table, particularly due to the presence of lots of zero values. 

I was wondering whether you felt that ANCOM was appropriate for these kind of analyses? From looking at the ANCOM paper I can't see why it wouldn't work, but I may be missing something?

**Comment by FrederickHuangLin** [comment]
Hi @Somebodyatthdoor,

This is a great question!

I don't see any problem implementing ANCOM in such a scenario. However, ANCOM is designed to address compositionally in microbiome data (such as the 16S OTU table). If your table is for presence/absence, I think implementing ANCOM is not necessary since there is no compositionality issue.

Best,
Huang
