### ISSUE TITLE
Questions about ANCOM-2.1

### ISSUE THREAD

**Issue by mnhuda** [FrederickHuangLin/ANCOM#4]
Thank you so much for developing ANCOM-2.1. In terms of speed, the ANCOM-2.1 is very fast compared to ANCOM-1, which is a great improvement. I have several questions and comments about the ANCOM-2.1. Please see below. 

_Structural zeros_: How the asymptotic lower bound is determined? If I understand correctly, any taxon having lower than 2.5% in one group (eg; placebo) is considered as structural zeros. Is there any minimum cutoff for the structural zero taxa above which it must present in the other group(s) (eg; treatment group)?

_W value cutoff_: What is the recommended “W” value cutoff (eg; W > 0.9, W > 0.6, or lower) for determining significantly differential abundance? Can we use any W value cutoff above the background? 

_False-negative_: I know the false positive rate is very low in ANCOM. I was wondering what is the false-negative rate in ANCOM-2.1. In the first example on the GitHub tutorial, you compared microbiota between two subjects and found only 5 taxa differentially abundant at W>0.9 and only 9 taxa at W >0.6. To me, it seems that we should observe more differentially abundant taxa between two individuals.

_Assumptions_: Do we need to check the assumption for ANOVA or mixed effect models?

_Linear regression_: since ANOVA and linear regression (lm) are similar, I was wondering if we can do linear regression in ANCOM-2.1. Linear regression will allow us to analyze continuous variables.

_Error_: For Random coefficients/slope model I got the following error message “Error in lme.formula(fixed = tformula, data = data.frame(x, alr_data,  :  nlminb problem, convergence error code = 1   message = iteration limit reached without convergence (10)”. Would you please check?

Thank you so much.

**Comment by FrederickHuangLin** [comment]
Hi,

Thank you for using ANCOM! Please see the answers below.

1. The preprocessing step is based on a separate paper [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/). More specifically, `neg_lb = TRUE` indicates you are using both criteria stated in section 3.2 of [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) to detect structural zeros; Otherwise, `neg_lb = FALSE` will only use the equation 1 in section 3.2 of [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) for declaring structural zeros.

2. Based on the author's recommendation, `detected_0.7` is commonly used. However, you can choose `detected_0.8` or `detected_0.9` if you want to be more conservative at your results (smaller FDR), or use `detected_0.6` if you would like to allow more flexibility (larger power). 

3. ANCOM 2.1 is a newer version of ANCOM script, the **ONLY** difference is the logic of writing codes. We also perform some benchmark analyses, their results are pretty much the same. I think given the strong FDR control of ANCOM, you can expect it reports less significant taxa as compared to other methods.

4. Although it is more statistically rigorous to check the assumptions of the model, if you check the ANCOM formula (see equation (8) of the [ANCOM supplementary material](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) ), as it computes the ratio for every pair of taxa, it can be tedious if you check every single model. Therefore, we usually don't do that (neither do most of the methods in analyzing high-throughput data).

5. As you can see in the formula (equation (8) of the [ANCOM supplementary material](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) ), ANCOM does allow for **adjusting**  continuous variables; However, your main variable of interest so far should be categorical. We are developing a new algorithm to overcome this issue, stay tuned!

6. Thanks for pointing out! This error is due to the function of fitting linear fixed effects model in R `nlme::lme`, not because of the ANCOM main function. Basically it means the algorithm used in `lme` does not converge, you can increase the maximum number of iterations for `nlminb`, see `nlmeControl()`, the default value is 50, you can try with larger values. I will make the tutorial more clear in this example.

Hope it helps,

Huang

**Comment by mnhuda** [comment]
Thank you so much Huang for your reply. 

I believe the detection 0.7 came from some empirical testing on a data set. I was wondering if we take some better approach. I think we should permute microbiota data (or phenotype data), perform ANCOM-2.1 1000 times to get a null distribution for W value, and then determine the W threshold at the 95th percentile of the null distribution. I know it will be computationally extensive. However, now most of the universities use high performance cluster computing systems. Additionally, people can use AWS. We can make it faster by using array job.

Regards,
Nazmul

**Comment by FrederickHuangLin** [comment]
Hi Nazmul,

I think it is a great idea!

However, based on the simulation studies performed in the [ANCOM](https://www.tandfonline.com/doi/full/10.3402/mehd.v26.27663) paper, it turns out that choosing `detected_0.7` has already returned a comparable power as all other methods while keeping the FDR under control; I think that is the reason why the author did not precede to do the permutations.

One more thought from me is that, as you can see from the ANCOM algorithm, itself is already more computationally intensive than other existing methods; It is probably fine if we do permutations in one single dataset, but there could be much more time-consuming if we want to benchmark it with other methods through simulations.

I will inform the author of the possibility of permutations and parallel computing.

Best,

Huang
