### ISSUE TITLE
conceptual question on whether to adjust for "covariates"

### ISSUE THREAD

**Issue by samd1993** [FrederickHuangLin/ANCOM#9]
Hi,

First of all, really appreciate the release of this detailed github! 

I know this may not be the place to ask this since this is for technical issues but thought I would shoot anyway. I have data from an ecological microbiome experiment I conducted a while back with "clustered data" I believe. The experiment's aim was to determine the effects of enriched nutrients on the microbiome of the fish's gut, stomach, and territory algae (food source). Since I have microbiome data from three sources with "nutrients" as the independent variable of focus, I am looking to utilize ANCOM 2.0 since it allows for mixed effects. 

My main hope is to use an overarching analysis for this data instead of subsetting it by microbiome type. Would the "adjusting for covariates" your analysis provides be acceptable to use for this type of data? Microbiome type would be the adjusted covariate and nutrients would be the experimental variable. 

Apologies if this is not clear or if you need more information to answer this. Any information or guidance on the matter would be appreciated.
Cheers,
Sam

**Comment by FrederickHuangLin** [comment]
Hi Sam,

Thank you for your interest in using ANCOM!

ANCOM is doing what we called the differential abundance (DA) analysis. Although it is not rigorously correct, conceptually, the ANCOM model can be seen as:

`y ~ x1 + x2 + x3 + ...`

Here, `y` is the microbial absolute abundances; say `x1` is the parameter of interest (for example, nutrients which can be specified in `main_var` in the `ANCOM` function; ); and `x2`, `x3` etc. are adjusting variables which can be specified in `adj_formula` in the `ANCOM` function (for example, location, year, etc.).

Based on your description, it seems your objective is the other way around of DA analysis, in which `y` is nutrients, and microbial absolute abundances are somewhere on the right-hand side of the model. Unfortunately, this is not what ANCOM is designed for. Your problem is more like a classification problem to me. For your information, you can check whether machine learning methods (see [QIIME2](https://docs.qiime2.org/2020.2/tutorials/sample-classifier/) and [LEfSe](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3218848/)) are suitable in your situation.

Hope it helps,

Best,

Huang

**Comment by samd1993** [comment]
Hi Huang,

Thank you for the quick feedback. I may be a bit confused here but I believe my dependent variable is still the microbiome and nutrients is simply a factor I am manipulating to see its effects on microbiome composition and diversity. This would make my "y" microbial abundance correct?

I will look into machine learning methods as that may be useful. However, I am still curious whether I can use ANCOM while adjusting for "microbiome type"?

**Comment by FrederickHuangLin** [comment]
Hi Sam,

Sorry for misunderstanding your question. 

In this condition, you are absolutely right, you can perform ANCOM while adjusting for "microbiome type" by specifying:

`main_var = "nutrient"; adj_formula = ”type”`

Hope it helps :)

Huang
